# This is intended to execute the tests scripts.
name: "Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PY_VERSION: 3.6
  YK_FACE_BASE_URL: ${{ secrets.YK_FACE_BASE_URL }}
  YK_FACE_X_API_KEY: ${{ secrets.YK_FACE_X_API_KEY }}

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install dependencies
      - run: pip install -e .[tests]

      - name: Execute Tests
      - run: pytest ./tests
